### ISSUE TITLE
How to add multiple trendlines on a single graph

### ISSUE THREAD

**Issue by ghost** [PhDMeiwp/basicTrendline#3]
I have few queries can you please address these;

1. How can I plot or display more than one trendline in same plot (Like A vs B, C and D plot) and with different equations (like line2p for A vs B, line3p for A vs C and A vs D)
2. How can I display only R square value and not the p value 
3. How to add subscript or superscript in x/y-axis title. 

Thanks

**Comment by PhDMeiwp** [comment]
1. alternatively, see "[case 5]" in R package "basicTrendline2" ([https://github.com/PhDMeiwp/basicTrendline2](https://github.com/PhDMeiwp/basicTrendline2)).

2. update the package "basicTrendline" to version 2.0.5, where the original 'show.Rpvalue' was divided into tow parameters named 'show.Rsquare' and 'show.pvalue'. e.g.,
trendline(x,y, show.Rsquare = TRUE, show.pvalue = FALSE)

3. use "expression()" for "xlab" or "ylab". e.g.,  
trendline(x,y, xlab =expression('X'[2]), ylab = expression(paste(delta^15,"N")))
